---

# CL: Curriculum Learning
# IL: Individual Learning

JOBS:    
  # Examples of CL
  - MODEL: "bsn"
    DATASET: "timit"
    STEGANOGRAPHY: "lsb-rs"
    TRAIN:
      LEARNING_TYPE: "CL"
      BPS: [0.5, 0.4, 0.3, 0.2, 0.1]
      EPOCHS: [200, 200, 200, 200, 200]
      CL_INIT_BPS: 0.5
      APPLY_AUGMENTATION: True
    TEST:
      N_REPEATS: 100

  - MODEL: "bsn"
    DATASET: "timit"
    STEGANOGRAPHY: "lsb-ms"
    TRAIN:
      LEARNING_TYPE: "CL"
      BPS: [0.5, 0.4, 0.3, 0.2, 0.1]
      EPOCHS: [1000, 500, 500, 500, 500]
      CL_INIT_BPS: 0.5
      APPLY_AUGMENTATION: True
    TEST:
      N_REPEATS: 100

  - MODEL: "linnet"
    DATASET: "timit"
    STEGANOGRAPHY: "lsb-rs"
    TRAIN:
      LEARNING_TYPE: "CL"
      BPS: [0.5, 0.4, 0.3, 0.2, 0.1]
      EPOCHS: [1000, 500, 500, 500, 500]
      CL_INIT_BPS: 0.5
      APPLY_AUGMENTATION: True
    TEST:
      N_REPEATS: 100

  # Examples of IL
  - MODEL: "srnet"
    DATASET: "timit"
    STEGANOGRAPHY: "lsb-ms"
    KERNEL_SIZE: 3
    TRAIN:
      LEARNING_TYPE: "IL"
      BPS: 0.5
      N_EPOCHS: 1000
      APPLY_AUGMENTATION: True
    TEST:
      N_REPEATS: 100

  - MODEL: "linnet"
    DATASET: "timit"
    STEGANOGRAPHY: "hide4pgp"
    TRAIN:
      LEARNING_TYPE: "IL"
      BPS: 0.5
      N_EPOCHS: 1000
      APPLY_AUGMENTATION: True
    TEST:
      N_REPEATS: 100


# Default values
MODEL: "bsn"             # Placeholder
DATASET: "timit"         # Placeholder
STEGANOGRAPHY: "lsb-ms"  # Placeholder
BPS: 0.5
SEED: 1

TRAIN:
  N_EPOCHS: 1000
  APPLY_AUGMENTATION: True

  FREQ_EPOCH_CKPT: 1
  FREQ_EPOCH_VALID: 1
  FREQ_EPOCH_TEST: 1  
  USE_NORM: False
  CROP_SIZE: 8000
  CLIP_GRAD_VALUE: 0
  LEARNING_RATE: 1e-4
  
  LOAD_POLICY: "min-loss"
  
  AUGMENTATION:
    PROB_FLIP_LR: 0.5
    PROB_CUTOUT: 0.1
    PROB_FLIP_SIGN: 0.1
    PROB_SHUFFLE_SEGMENTS: 0.1
    PROB_ADD_NOISE: 0.1
    NUM_SEGMENTS: 8
    CUTOUT_RATIO: 0.01

TEST:
  N_REPEATS: 0
  USE_NORM: False

  LOAD_POLICY: "min-loss"

SYSTEM_SPECIFIC:
  WRITE_YOUR_SYSTEM_HOSTNAME:
    USE_TENSORBOARD: False
    USE_VISDOM: False
    VISDOM_CLEAR_ENVS: False

    BATCH_SIZE: 16
    N_WORKERS: 8
    DROOT_DATASET: "YOUR_DIR_PATH"     # e.g.) /home/user/dataset/audio"
    DROOT_CKPT: "YOUR_DIR_PATH/ckpts"  # e.g.) /home/user/repos/bsn/ckpts
    DROOT_TEST: "YOUR_DIR_PATH/tests"  # e.g.) /home/user/repos/bsn/tests
        
    DPATH_COVER: ""  
    DPATH_STEGO: ""

    DPATH_TEST: "YOUR_DIR_PATH/tests"  # e.g.) /home/user/repos/bsn/tests
    DPATH_LOAD_CKPT: ""
    DPATH_SAVE_CKPT: ""

